### ISSUE TITLE
TypeError: 'unsupported operand type(s) for @: '_core_pybinds.sophus.SE3d' and '_core_pybinds.sophus.SE3d'

### ISSUE THREAD

**Issue by graciegumm** [facebookresearch/projectaria_tools#20]
Hi, I am facing a TypeError when running 'mps_quickstart_tutorial.ipynb'. 

I get the following error when running the line "cam_frustums[i] = build_cam_frustum(pose.transform_world_device)": unsupported operand type(s) for @: '_core_pybinds.sophus.SE3d' and '_core_pybinds.sophus.SE3d

Thank you!

**Comment by SeaOtocinclus** [comment]
We are changing our Sophus API, please use last stable version (you can checkout at tag 1.1.0)
See here https://github.com/facebookresearch/projectaria_tools/issues/19

**Comment by SeaOtocinclus** [comment]
@graciegumm Thank you for your feedback.
We have now released v1.2.0 -> https://github.com/facebookresearch/projectaria_tools/releases/tag/1.2.0
Python notebooks and `pip install projectaria-tools` are now matching!

Closing for now, feel free to re-open if you encounter any issue.

**Comment by graciegumm** [comment]
Hi, I am using v1.2.0 now and I am still getting the same error in this issue (#20) and the error in issue #19.

**Comment by chpeng-fb** [comment]
@graciegumm Thank you for reporting this issue. The updated github mps_quickstart_tutorial from github and the latest pypi package should work together. If you are still have the same issue, it might because the there is a mismatch of python module and the github version. This could be due to the jupyter notebook not coming from the virtual environment (when you have an older version installed in non-virtual environment, jupyter defaults to that env instead of the current venv). You can try to run the notebook in the specific virtual environment 
```
source ~/your_virtual_env/bin/activate

cd projectaria_tools/core/examples
python3 -m jupyter notebook mps_quickstart_tutorial.ipynb
```

**Comment by graciegumm** [comment]
@chpeng-fb The issue was on my end and is resolved now, thank you!
